branch-defaults:
  ble-im4:
    environment: Achiever-dev
environment-defaults:
  Achiever-dev:
    branch: null
    repository: null
global:
  application_name: Achiever
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.8.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
